### ISSUE TITLE
Ausrichtung / Ziele

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-dsl#11]
Vom Council:

Die am Anfang formulierten Ziele
understand where a DSL fits into an overall architecture,
design useful and user-friendly DSL in a systematic fashion, and
consider DSLs as an integral technique in architecture design.
wären sinnvoll, werden aber durch diese Ausrichtung des Modul gerade
nicht deutlich. Auch das ein (1)-Thema. Das Modul hat so nicht die
richtige Ausrichtung.

**Comment by larsrh** [comment]
Dieses Thema wird in mehreren Lernzielen besprochen:

> Know possible requirements and conditions that might make a DSL a
  sensible architectural decision, such as an insufficiently
  expressive implementation language, the need for complex
  user-defined rules, the need to restrict behavior of parts of the
  software, or the need to make parts of the software analysable in
  non-trivial ways. [LG 1-1]
>
> Understand that syntax is a matter of both ergonomics and taste, and
  thus the subject of requirements. [LG 2-1]
>
> Know the difficulty of good language design, and its impact on
  architectural decisions, in particular whether to implement an
  embedded or stand-alone DSL, and whether to re-use design or
  implementation elements from existing languages. [LG 4-1]
