### ISSUE TITLE
Spezifische Tools?

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-dsl#5]
Vom Council:

Bei den Tools ist von Kernkonzepten die Rede - können wir die Toolsicht ausdehnen und spezifische Tools und Sprachen besprechen? Die Lernziele sind hier recht generisch, lassen in der Umsetzung viel zu. In den Terms und Principles tauchen auch keine konkreten Sprachen oder Tools auf. Generell wäre es hier möglich 00-Sprachen, funktionale Sprachen, Tools die spezifisch als Parser, Generator etc. verwendet werden können, IDEs, Datenstruktur-Möglichkeiten usw. zu erwähnen und zu besprechen.

**Comment by larsrh** [comment]
iSAQB-Curricula sollten nach Vorgabe nicht Technik- oder Tool-spezifisch sein. Schulungsanbieter können in ihren Schulungen diese Aspekte individuell ausgestalten. Das vorliegende Curriculum ist derart spezifiziert, dass Raum für verschiedene Technologien bleibt.

**Comment by mikesperber** [comment]
Nach Rückmeldung von Stefan Toth haben wir nun doch einige konkrete Tools beispielhaft verlinkt.
