### ISSUE TITLE
Business-Case

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-dsl#7]
Vom Council:

Es felt eine klare Darstellung der Pros und Cons von DSLs. Somit vermisse ich eine Guidance oder Hilfestellung, wann es sich lohnt über DSLs tatsächlich nachzudenken. Es gibt aus meiner Erfahrung heraus gute Einsatzszenarien für DSLs (.B. als Schnittstellenabstraktion, im Bereich der Produktentwicklung als Kundenschnittstelle, als /"'Implementierung" von Testdaten oder für Low-Code/No-Code Systeme). Diese müssten (wie Ross und Reiter) eigentlich benannt werden und dann gegen andere Alternativen (.B. Fluent-Interface) abgegrenzt werden. Gleichfalls müsste auf die Nachteile hingewiesen werden. Eine Abstraktion mittels DSL erfordert auch immer ein Team, was diese wartet, weiterentwickelt und betreibt.

**Comment by larsrh** [comment]
Tradeoffs werden im Kapitel 1 erschöpfend erläutert.
