### ISSUE TITLE
Abgrenzung zu/Synergien mit DDD

### ISSUE THREAD

**Issue by mikesperber** [isaqb-org/curriculum-dsl#9]
Vom Council:

Für eine Einordnung von DSL in unsere Wissenslandkarte würde ich mir
wünschen, dass eine Positionierung des Themas Teil der Schulung ist. So
sehe ich .B. die Beziehungen von DSL und DDD - oder auch deren
Unterschiede - als wichtigen Aspekt, was eine Kommunikation des Moduls
m Gesamtzusammenhang erleichtern könnte.

**Comment by larsrh** [comment]
Abgefrühstückt in:

> Know the basic principles of Domain-Driven Design and how they relate to domain-specific languages. [LG 1-3]
>
> Understand the relationship between the ideas of "closure of operations" in Domain-Driven Design and compositionality. [LG 4-3]

Außerdem in den Vorbedingungen des Moduls:

> tactical domain-driven design
